# Generated by Django 5.2.12 on 2026-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="license_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
