# Generated by Django 5.2.12 on 2026-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_license_plate_userprofile_vehicle_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="driving_license_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_approved_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="license_upload",
            field=models.ImageField(
                blank=True, null=True, upload_to="driver_docs/licenses/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rc_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rc_upload",
            field=models.ImageField(blank=True, null=True, upload_to="driver_docs/rc/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
