# Generated by Django 5.2.12 on 2026-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_driving_license_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
