services:
  - type: web
    name: kokrajhar-cab
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne cabapp.asgi:application --port $PORT --bind 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kokrajhar-cab-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: kokrajhar-cab-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9"

databases:
  - name: kokrajhar-cab-db
    plan: free

  - type: redis
    name: kokrajhar-cab-redis
    plan: free
    maxmemoryPolicy: noeviction
