# Generated by Django 5.2.12 on 2026-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup", models.CharField(max_length=200)),
                ("drop_location", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
