# Generated by Django 5.2.12 on 2026-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_ride_passenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
