# Generated by Django 5.2.12 on 2026-03-19 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_alter_ride_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ride",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
