# Generated by Django 5.2.12 on 2026-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_ride_created_at_ride_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="estimated_fare",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ride",
            name="pickup_distance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ride",
            name="travel_distance",
            field=models.FloatField(default=0.0),
        ),
    ]
