# Generated by Django 5.2.12 on 2026-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_ride_estimated_fare_ride_pickup_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="ride_type",
            field=models.CharField(
                choices=[("motorbike", "Motorbike"), ("car", "Car")],
                default="car",
                max_length=20,
            ),
        ),
    ]
